postgresql:
  image: postgres:10-alpine
  ports:
    - 5433:5432
  environment:
    - PGDATA=/postgresql
    - POSTGRES_PASSWORD=password
  restart: unless-stopped
  volumes:
    - ./tmp/data/postgresql:/postgresql
redis:
  image: redis:latest
  ports:
    - 6380:6379
  volumes:
    - ./tmp/data/redis:/var/lib/redis
